name: CI

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true # We are using flakes

    - name: Run tests
      run: ./run-tests.py
